server:
  port: 8888

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_base
    username: root
    password: quang123
    driver-class-name: com.mysql.cj.jdbc.Driver
